services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: restaurant_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file: ./.env.local
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  postgres-data:
